### ISSUE TITLE
closures with cf is not supporting move in captures

### ISSUE THREAD

**Issue by spinorx** [rpz80/cf#11]
Sample code:
```
#include <future>

#include "cf/cfuture.h"
#include "cf/sync_executor.h"

class Foo {
};

int main(int argc, char* argv[]) {
  std::unique_ptr<Foo> u_foo = std::make_unique<Foo>();
/*  cf::sync_executor executor;
  cf::async(executor, [c_u_foo = std::move(u_foo)] {
    return cf::unit();
  });*/
  std::async(std::launch::async, [c_u_foo = std::move(u_foo)] {
    return cf::unit();
  });
}
```

Same capture works with std::async,  but not with cf::async.  Error I get:

In file included from experimental/cf_test/main.cc:3:
In file included from /usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/future:38:
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/functional:1711:10: error: call to implicitly-deleted copy constructor of '(lambda at external/com_github_spinorx_cf/cf/cfuture.h:891:17)'
            new _Functor(*__source._M_access<_Functor*>());
                ^        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/functional:1746:8: note: in instantiation of member function 'std::_Function_base::_Base_manager<(lambda at external/com_github_spinorx_cf/cf/cfuture.h:891:17)>::_M_clone' requested here
              _M_clone(__dest, __source, _Local_storage());
              ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/functional:2256:33: note: in instantiation of member function 'std::_Function_base::_Base_manager<(lambda at external/com_github_spinorx_cf/cf/cfuture.h:891:17)>::_M_manager' requested here
            _M_manager = &_My_handler::_M_manager;
                                       ^
external/com_github_spinorx_cf/cf/cfuture.h:891:17: note: in instantiation of function template specialization 'std::function<void ()>::function<(lambda at external/com_github_spinorx_cf/cf/cfuture.h:891:17), void, void>' requested here
  executor.post([promise_ptr, f = std::forward<F>(f), args...] () mutable {
                ^
experimental/cf_test/main.cc:14:7: note: in instantiation of function template specialization 'cf::async<cf::sync_executor, (lambda at experimental/cf_test/main.cc:14:23)>' requested here
  cf::async(executor, [c_u_foo = std::move(u_foo)] {
      ^
external/com_github_spinorx_cf/cf/cfuture.h:891:31: note: copy constructor of '' is implicitly deleted because field '' has a deleted copy constructor
  executor.post([promise_ptr, f = std::forward<F>(f), args...] () mutable {
                              ^
experimental/cf_test/main.cc:14:24: note: copy constructor of '' is implicitly deleted because field '' has a deleted copy constructor
  cf::async(executor, [c_u_foo = std::move(u_foo)] {
                       ^
/usr/bin/../lib/gcc/x86_64-linux-gnu/5.4.0/../../../../include/c++/5.4.0/bits/unique_ptr.h:356:7: note: 'unique_ptr' has been explicitly marked deleted here
      unique_ptr(const unique_ptr&) = delete;
      ^
1 error generated.

**Comment by rpz80** [comment]
Thank you! [Fixed](https://github.com/rpz80/cf/commit/6f7918e9294cbd179e79e2c7b9bca09220035903).
