### ISSUE TITLE
Random promise_already_satisfied exception and data race

### ISSUE THREAD

**Issue by kefky** [rpz80/cf#2]
Hello, we've been using this library as this is a very nice way to write cleaner asynchronous code.

Unfortunately, it looks like there is an issue when using .then() where an internal promise gets set twice.

This simple piece of code can help reproducing it very reliably:
```
#include <string>
#include "cf/cfuture.h"

int main(int argc, char* argv[]) 
{
    for (int i = 0; i < 2000; i++)
    {
        auto future = cf::async([] { return 1; })
        .then([](cf::future<int>)  { return 2; });
    }

    return 0;
}
```
This throws an exception (compiled with clang) :
`libc++abi.dylib: terminating with uncaught exception of type cf::future_error: promise_already_satisfied`

Running clang's ThreadSanitizer shows a data race with the .then() callback that seems related:
```
Write of size 8 at 0x7d4000017998 by main thread (mutexes: write M753):
template<typename F>
void set_callback(F&& f) {
    std::unique_lock<std::mutex> lock(mutex_);
    cb_ = std::forward<F>(f);    <<<<<<<<<<<<<<<   Write callback
    lock.unlock();
    if (satisfied_)
      cb_();
  }
```

```
Previous read of size 8 at 0x7d4000017998 by thread T9:
void set_ready(std::unique_lock<std::mutex>& lock) {
    satisfied_ = true;
    cond_.notify_all();
    lock.unlock();
    cb_();    <<<<<<<<<<<<<<<  Access callback with mutex unlocked
}
```

It doesn't look like an easy fix as any change with the mutexes has lots of implications

**Comment by kefky** [comment]
Here are Thread Sanitizer logs
[sanitizer.txt](https://github.com/rpz80/cf/files/799762/sanitizer.txt)

**Comment by rpz80** [comment]
Thank you for the feedback. Fixed, relevant UT [added](https://github.com/rpz80/cf/commit/cfeaba53ca322d12610f5b0fc1e3f14bbe2e053c).

**Comment by kefky** [comment]
Thank you for the quick fix, looks like the issue is solved
