### ISSUE TITLE
get value from inner future in future<T> then_impl

### ISSUE THREAD

**Issue by dkapicak** [rpz80/cf#4]
In this example:

cf::make_ready_future(true).then(threadpool, [](cf::future<bool> f) {

		auto f1 = async(threadpool, [] {....});
                auto f2 = async(threadpool, [] {....});
                auto f3 = async(threadpool, [] {....});
                auto f4 = async(threadpool, [] {....});

		return cf::when_all(f1,f2,f3,f4);
	}).then(threadpool, [](cf::future<std::tuple<...>> f) {
	        //...
	});
is "when_all" future returned immediately from lambda and get() method is called to potentionally unset future: p.set_value(inner_f.get()); (line 555 in cfuture.h). 
IMHO it mens there is one extra thread which simply wait for f1, f2, f3 and f4 futures completion. 
It is desired behaviour?

**Comment by rpz80** [comment]
What do you mean by "extra one"? Yes, the executor thread will wait till `when_all` future becomes ready, but it's kind of what it is designed for - to perform long-lasting heavy jobs. But the main thread is free to continue its work (unless you put `wait()` in the end of your example of course).

**Comment by dkapicak** [comment]
Firstly, I would like to thank you  for your Future implementation. It helps me so much. I mean exactly what you said. Executor thread will wait till when_all future becomes ready. What do you think about this: call inner_f.then([...] (future<T> f) { p.set_value(f.get())}) instead of p.set_value(inner_f.get())? Aftet this modification there will be some caint of "internall task" which will be posted to executor after inner_f becomes ready.

**Comment by rpz80** [comment]
Seems to make sense. I don't see any cons at the moment. So here is the [fix](https://github.com/rpz80/cf/commit/67d47f1b02a00f5fbd3230a291924cc4baace44a).
