### ISSUE TITLE
wait_for and wait_until template ae uncompilable

### ISSUE THREAD

**Issue by dkapicak** [rpz80/cf#5]
I have compile template error with wait_for and wait_until template. You access to state_ methods via operator . , but state_ is shared_ptr so you must use operator->

void wait_for(const std::chrono::duration<Rep, Period>& timeout) {
    check_state(state_);
    **state_.wait_for(timeout);**
  }

**Comment by rpz80** [comment]
Weird.. Thank you! [Fixed](https://github.com/rpz80/cf/commit/b5d9f776795535f113e7dfe6cb91737b3fe063c5)
