### ISSUE TITLE
watcher 100% core usage

### ISSUE THREAD

**Issue by dkapicak** [rpz80/cf#6]
I'm seeing 100% core usage after time_watcher construction. I think that problem is in wait_until wakeuptime value (time_point::max()). I debugged msvc2015:

```
template<class _Clock,
		class _Duration,
		class _Predicate>
		bool wait_until(
			unique_lock<mutex>& _Lck,
			const chrono::time_point<_Clock, _Duration>& _Abs_time,
			_Predicate _Pred)
		{	// wait for signal with timeout and check predicate
		typename chrono::time_point<_Clock, _Duration>::duration
			_Rel_time = _Abs_time - _Clock::now();
		_STDEXT threads::xtime _Tgt = _To_xtime(_Rel_time);
		return (_Wait_until1(_Lck, &_Tgt, _Pred));
		}
```

and _To_xtime overflows, which results in undefined behavior, and the result is a negative time_point.

**Comment by rpz80** [comment]
Can't reproduce this on MSVS 2015 update 3 with this snippet:
``` 
  cf::time_watcher tw;
  auto p = std::make_shared<cf::promise<cf::unit>>();
  cf::future<cf::unit> f = p->get_future();
  tw.add([p]() mutable {
    p->set_value(cf::unit());
  }, std::chrono::seconds(100));
  f.wait();
```
Tried 64/32, debug/release. I have a few spurious wakeups but after that it stands still. Maybe they've already fixed that in update 3. What is your studio exact version and could you provide a reproducible code snippet?

**Comment by dkapicak** [comment]
```
int main()
{
    cf::time_watcher tw;
    using namespace std::chrono_literals;
    std::this_thread::sleep_for(10s);

    auto p = std::make_shared<cf::promise<cf::unit>>();
    cf::future<cf::unit> f = p->get_future();
    tw.add([p]() mutable {
        p->set_value(cf::unit());
  }, std::chrono::seconds(100));
  f.wait();
}
```
And You can see what watcher thread do until mainthread sleeps. My visual studio version is 2015 update 3

**Comment by rpz80** [comment]
Ok, fixed [here](https://github.com/rpz80/cf/commit/c0076d65de4a9058a97de741307f9feff7733ce4) and [here](https://github.com/rpz80/cf/commit/e29fee686493b986fd3a1cc2ce8cb06f786e8e45).

**Comment by daniellll3266** [comment]
Thank you but cf::future::timeout is not compilable because time_watcher::add interface is changed
const std::chrono::duration<Rep, Period>& timeout to std::chrono::milliseconds timeout
