### ISSUE TITLE
Endless loop when an exception is thrown using cf::when_all

### ISSUE THREAD

**Issue by Wizermil** [rpz80/cf#8]
Hi,

I found this bug while testing my error management code ;)

````C++
#include <iostream>
#include <cf/cfuture.h>
#include <exception>
#include <cf/async_thread_pool_executor.h>

int main(int argc, const char * argv[]) {
    std::vector<cf::future<cf::unit>> listFutures;
    listFutures.reserve(10);
    for (int i = 0; i < 10; i++) {
        listFutures.push_back(cf::async([i]() {
            if (i == 7)
                throw std::runtime_error("Error");
            return cf::unit();
        }));
    }
    try {
        cf::when_all(listFutures.begin(), listFutures.end()).get();
    } catch(std::runtime_error& e) {
        std::cout << "error= " << e.what() << std::endl;
    }

    return 0;
}
````

**Comment by rpz80** [comment]
Thank you! That was valuable. [Fixed](https://github.com/rpz80/cf/commit/32d47708ad24d48c3c0ff846b23d3f81657fa3fb)

**Comment by Wizermil** [comment]
I think there is a problem with your latest commit.
With the snippet below the exception is not rethrow when calling get as expected and the then statement is executed
```C++
    try {
        cf::async([]() {
            throw std::runtime_error("Error");
            return cf::unit();
        }).then([](auto res) {
            std::cout << "then" << std::endl;
            return cf::unit();
        }).get();
    } catch (std::runtime_error& e) {
        std::cout << "error= " << e.what() << std::endl;
    }
```
BTW cf::when_all doesn't wait endlessly anymore but the exception is not escalated high enough to be rethrown when I call method: get.

I'm sorry for bringing the bad news

**Comment by rpz80** [comment]
Ok, I think this needs some explanation. The original problem was the inconsistent behavior of the continuation when exception'd been thrown in continuation callback and when it hadn't. In the first case continuation handler wasn't called at all, so you were not able to know that exception had been thrown when you were inside your then callback. I consider this bad.

Now to fix your code you should add res.get() (or wait) to your then callback. In this case exception will be propagated as expected.

**Comment by Wizermil** [comment]
My bad I didn't explain my problem clearly.

My original problem is that the program wasn't able to finish because when the exception was thrown instead of being rethrow by the get it was stuck on wait instruction endlessly.
I was expecting to be able to catch the exception and close the program.
Like in your readme example where you expect the continuation of future to stop at the fist exception thrown and handle the error globally with one simple try/catch.

Did I misunderstand how future should work?

**Comment by rpz80** [comment]
Let's take a look at your example before and after last commit. Before last commit:
``` c++
try {
    cf::async([]() {
        throw std::runtime_error("Error");
        return cf::unit();
    }).then([](auto res) {
        std::cout << "then" << std::endl;   // This Code is not executed at all,
        return cf::unit();                  // only exception is propagated.
    }).get();
} catch (std::runtime_error& e) {
    std::cout << "error= " << e.what() << std::endl;
}
```
After:
``` c++
try {
    cf::async([]() {
        throw std::runtime_error("Error");
        return cf::unit();
    }).then([](auto res) {
        std::cout << "then" << std::endl;  // Now this code is called regardless exception
        res.get();                         // <-- And you need this line to let the exception, stored in
        return cf::unit();                 // res out. After this it will be caught in your catch block.
    }).get();
} catch (std::runtime_error& e) {
    std::cout << "error= " << e.what() << std::endl;
}
```

Actually there is a choice here between first scenario and second. But most of the code that uses `then()` (for example implementations of `when_all()` and `when_any()`) rely on the fact that continuation will be called in any case whether the exception's been thrown or not. Does it make sense?

I've updated readme btw.

**Comment by Wizermil** [comment]
I understand but the 2nd option you chose mean that we have to write a lot of extra boilerplate code making the usage of future much less attractive.

Interrupting a sequence with an exception seems more reasonable because it's explicit and easy to read and understand.
Moreover with your previous design we already had the choice of returning any error codes and handling it in the continuation.

For when_all case I expect to receive the 1st exception caught to be rethrown when I call get on cf::future<std::vector<cf::future<T>>> (at the end of the execution of all the future of course) and if I want to have the detail per future I can always iterate over the vector.
I have the feeling that a try/catch in when_all would work??
```C++
  template<typename InputIt>
  auto when_all(InputIt first, InputIt last)
  -> future<std::vector<typename std::iterator_traits<InputIt>::value_type>> {

...

    for (; first != last; ++first, ++index) {
      shared_context->result.push_back(std::move(*first));
=>      try { // Proposition Handle Exception in when_all 
          shared_context->result[index].then(
          [shared_context, index]
          (typename std::iterator_traits<InputIt>::value_type f) mutable {
            {
              std::lock_guard<std::mutex> lock(shared_context->mutex);
              shared_context->result[index] = std::move(f);
              ++shared_context->ready_futures;
              if (shared_context->ready_futures == shared_context->total_futures)
                shared_context->p.set_value(std::move(shared_context->result));
            }
            return unit();
          });
=>      } catch(...) {
=>        // Handle shared_context->result + shared_context->p.set_exception
=>      }
    }

```

**Comment by rpz80** [comment]
> I have the feeling that a try/catch in when_all would work??

Unfortunately it is not that simple )

But your point about redundant boilerplate code makes sense. I'll see what I can do.

**Comment by dkapicak** [comment]
I had similar problem so I implemented on_failure() callback. I think that failure callback is possible solution for this problem.

**Comment by Wizermil** [comment]
I had a better look at the code and indeed it's much more complicated than try/catch 😊

I don't know if the committee in charge of future for C++20 has a response to how to handle exception but [Facebook with Folly](https://github.com/facebook/folly/tree/master/folly/futures) chose to implement .onError like @daniellll3266 suggested

**Comment by rpz80** [comment]
I think i've fixed the issue. Check `exceptions_in_cb` branch please. 
Following is fixed:
1. this will throw as expected
```c++
    try {
        cf::async([]() {
            throw std::runtime_error("Error");
            return cf::unit();
        }).then([](auto res) {
            std::cout << "then" << std::endl;
            return cf::unit();
        }).get();
    } catch (std::runtime_error& e) {
        std::cout << "error= " << e.what() << std::endl;
    }
```
2. this won't hang
```
    try {
        cf::when_all(listFutures.begin(), listFutures.end()).get();
    } catch(std::runtime_error& e) {
        std::cout << "error= " << e.what() << std::endl;
    }

```

I'd like to notice though that this:
```c++
    try {
        cf::when_all(listFutures.begin(), listFutures.end()).get();
    } catch(std::runtime_error& e) {
        std::cout << "error= " << e.what() << std::endl;
    }
```
won't throw as you may expect even if one (or more) of the stored futures holds exception within. And I believe it is a correct behavior, because future returned by `when_all()` and futures stored in a result are completely unrelated. What shall throw is `get()` called with the exceptional future stored inside result vector.

**Comment by Wizermil** [comment]
Hi,

Thanks for the update.

However when I tested the case below I experienced something different than what I was expecting. The continuation was executed but from my naive understanding I was expecting the exception to stop the execution.
```c++
    try {
        cf::async([]() {
            throw std::runtime_error("no then");
            return cf::unit();
        }).then([](auto) {
            std::cout << "then" << std::endl;
            return cf::unit();
        }).get();
    } catch(std::exception& e) {
        std::cout << "Error=" << e.what() << std::endl;
    }
```
output
```
then
Error=no then
```

for when_all it's ok I just used a continuation to throw the exception
```c++
        .then([](auto responses) {
            for (auto& res : responses.get())
                res.get();
            return cf::unit();
        });
```

**Comment by rpz80** [comment]
Logic is the following:
- If you try to get value from future (argument of continuation), it will throw and be propagated as usual
- If future left untouched, than continuation will be executed till the end and exception will be propagated after it finishes.

So you will notified about the error either way (whether you `get()` value from continuation arg or not). And in the same time it enables you to do what you want with the arg future when you are inside continuation - that is what `when_*` functions and similar cases are based on.
